### ISSUE TITLE
Three pinpoints for item

### ISSUE THREAD

**Issue by seesmith** [UoEMainLibrary/LibraryMapping#74]
https://www.librarymaps.is.ed.ac.uk/?floor=3&library=main&identifier=lc_main&title=A+short+history+of+Finland&author=Frederick+Bernard.+Singleton&shelfmark=DL1032%20Sin.%20&view=full 

A Short History of Finland Shelfmark DL1032 Sin.

**Comment by charlotteyizhang** [comment]
Modified the shelve ranges.
